# Generated by Django 5.0.7 on 2024-08-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Data',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Note',
            new_name='Text',
        ),
    ]
